FROM debian:9-slim
RUN sed -i 's/deb.debian.org/archive.debian.org/g' /etc/apt/sources.list && \
    sed -i 's|security.debian.org/debian-security|archive.debian.org/debian-security|g' /etc/apt/sources.list && \
    sed -i '/stretch-updates/d' /etc/apt/sources.list
RUN apt-get update && apt-get install -y --allow-unauthenticated build-essential git
WORKDIR /build
ARG FAKETIME_SHA=HEAD
RUN git clone https://github.com/wolfcw/libfaketime.git . && \
    git checkout ${FAKETIME_SHA} && \
    CFLAGS="-DFAKE_STAT -DFAKE_PTHREAD -DFAKE_TIMERS -DFAKE_INTERNAL_CALLS -DFAKE_UTIME -pthread" make