package io.github.dimkich.integration.testing.message;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonRootName;
import com.fasterxml.jackson.annotation.JsonUnwrapped;
import io.github.dimkich.integration.testing.format.xml.attributes.BeanAsAttributes;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.Set;

/**
 * Data Transfer Object representing a message with headers and payload for integration testing.
 * <p>
 * This generic class is used to represent messages in integration tests, supporting both
 * inbound (received) and outbound (sent) messages. It provides structured access to message
 * metadata through headers and the actual message content through the payload.
 * <p>
 * The class is designed for serialization/deserialization from XML and JSON formats using
 * Jackson annotations. Headers are serialized as XML attributes when using {@link BeanAsAttributes},
 * while the payload is unwrapped in JSON representation.
 * <p>
 * Message headers can include standard properties such as topic, source, and key, as well as
 * custom headers. The {@code testInboundMessage} flag is used internally to distinguish test
 * messages from production messages and is excluded from JSON serialization.
 *
 * @param <T> the type of the message payload
 * @author dimkich
 * @see MessageHeadersDto
 */
@Data
@NoArgsConstructor
@AllArgsConstructor(onConstructor_ = @JsonCreator(mode = JsonCreator.Mode.DISABLED))
@JsonRootName(value = "message")
public class MessageDto<T> {
    /**
     * Header key constant used to identify test inbound messages.
     * <p>
     * This constant is used as a header key to mark messages that are generated by the
     * integration testing framework for inbound message processing. Messages marked with
     * this header are typically excluded from certain processing pipelines.
     */
    public static final String TEST_INBOUND_MESSAGE = "TEST_INBOUND_MESSAGE";

    /**
     * Set of Kafka headers that should be ignored when mapping Kafka messages to this DTO.
     * <p>
     * These headers are internal to Kafka and Spring Kafka framework and are typically
     * not relevant for test assertions or message comparison. They include metadata such
     * as consumer information, timestamps, offsets, and partition IDs.
     */
    private static Set<String> kafkaIgnoredHeaders = Set.of("id", "timestamp", "kafka_consumer", "kafka_timestampType",
            "kafka_receivedPartitionId", "kafka_receivedTimestamp", "__TypeId__", "kafka_groupId", "kafka_offset",
            "kafka_acknowledgment");

    /**
     * Message headers containing metadata such as topic, source, key, and custom headers.
     * <p>
     * Headers are serialized as XML attributes when using XML format due to the
     * {@link BeanAsAttributes} annotation.
     */
    @BeanAsAttributes
    private MessageHeadersDto headers = new MessageHeadersDto();

    /**
     * The message payload containing the actual data being sent or received.
     * <p>
     * The payload is unwrapped in JSON representation due to the {@link JsonUnwrapped}
     * annotation, meaning it will appear directly as properties rather than nested
     * under a "payload" field.
     */
    @JsonUnwrapped
    private T payload;

    /**
     * Flag indicating whether this message is a test inbound message.
     * <p>
     * When set to {@code true}, this message was generated by the integration testing
     * framework for inbound message processing. This flag is excluded from JSON
     * serialization but may be used internally to filter or process messages differently.
     */
    @JsonIgnore
    private boolean testInboundMessage;

    /**
     * Creates a new MessageDto with the specified payload.
     * <p>
     * Headers will be initialized to an empty {@link MessageHeadersDto} instance.
     *
     * @param payload the message payload, may be null
     */
    public MessageDto(T payload) {
        this.payload = payload;
    }
}
